# =============================================================================
# 🛠️  PRE-COMMIT CONFIG  - GOOGLE-SEARCH-AGENT  (Go project)
# =============================================================================
# Install / run:
#   pip install --user pre-commit
#   pre-commit install
#   pre-commit run --all-files
#
# To skip checks:
#   git commit -m "msg" --no-verify
#
# To update hooks:
#   pre-commit autoupdate
#   pre-commit install
#   pre-commit run --all-files
# =============================================================================

repos:
  # ---------------------------------------------------------------------------
  # 🔐 Security / secret detection
  # ---------------------------------------------------------------------------
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.27.2
    hooks:
      - id: gitleaks
        name: 🔐 Gitleaks – detect hard-coded secrets

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: detect-private-key
        name: 🔐 Detect private key
        types: [text]

  # ---------------------------------------------------------------------------
  # ❌ AI artefact & placeholder blockers
  # ---------------------------------------------------------------------------
  - repo: local
    hooks:
      - id: forbid-content-reference
        name: ❌ Forbid :contentReference
        entry: ":contentReference"
        language: pygrep
        types: [text]
        exclude: ^\.pre-commit-config\.yaml$

      - id: forbid-oai-citations
        name: ❌ Forbid OpenAI citations
        entry: '\[oaicite:\?\?\d+\]'
        language: pygrep
        types: [text]
        exclude: ^\.pre-commit-config\.yaml$

      - id: forbid-ai-stock-phrases
        name: ❌ Forbid AI stock phrases
        entry: "(?i)(as an ai language model|i don't have real-time information|my knowledge cutoff|i cannot browse the internet)"
        language: pygrep
        types: [text]
        exclude: ^\.pre-commit-config\.yaml$

      - id: forbid-placeholder-citations
        name: ❌ Forbid Placeholder citations
        entry: '\([A-Z][a-z]+,?\s+\d{4}\)'
        language: pygrep
        types: [text]
        exclude: ^\.pre-commit-config\.yaml$

      - id: forbid-source-placeholders
        name: ❌ Forbid source placeholders
        entry: '(?i)\(source:'
        language: pygrep
        types: [text]
        exclude: ^\.pre-commit-config\.yaml$

      - id: forbid-malformed-code-fences
        name: ❌ Forbid malformed code fences
        entry: "````+"
        language: pygrep
        types: [text]
        exclude: ^\.pre-commit-config\.yaml$

      - id: warn-ai-transitions
        name: ⚠️ Warn AI transition phrases
        entry: "(?i)(to summarize,|please note that)"
        language: pygrep
        types: [text]
        verbose: true
        exclude: ^\.pre-commit-config\.yaml$

  # ---------------------------------------------------------------------------
  # 🔤 Unicode text normalization (smart quotes, ligatures, exotic spaces)
  # ---------------------------------------------------------------------------
  - repo: https://github.com/sirosen/texthooks
    rev: v0.6.8
    hooks:
      - id: fix-smartquotes
        name: 📝 Normalize smart quotes
      - id: fix-ligatures
        name: 🔡 Normalize ligatures
      - id: fix-spaces
        name: ␣ Normalize Unicode spaces
      - id: forbid-bidi-controls
        name: 🚫 Forbid BiDi Unicode Controls

  # ---------------------------------------------------------------------------
  # 🧹 Generic formatting & whitespace
  # ---------------------------------------------------------------------------
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
        name: 🧹 Fix end of file
      - id: trailing-whitespace
        name: 🧹 Trim trailing whitespace
      - id: fix-byte-order-marker
        name: 🧹 Fix UTF-8 BOM
      - id: mixed-line-ending
        name: 🧹 Mixed line ending
        args: [--fix=lf]
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: forbid-new-submodules
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: check-xml

  # ---------------------------------------------------------------------------
  # 🐹 Go tool-chain (formatters + linters)
  # ---------------------------------------------------------------------------
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
      - id: go-imports
      - id: go-vet
      - id: golangci-lint
      - id: go-mod-tidy

  - repo: https://github.com/segmentio/golines
    rev: v0.12.2
    hooks:
      - id: golines
        name: 🧹 golines – wrap long lines
        args: ["--max-len=120","--base-formatter=gofumpt"]

# end of pre-commit-config.yaml
