# .golangci.yml
# Configuration for golangci-lint
# https://golangci-lint.run/usage/configuration/

run:
  # Timeout for the entire lint run
  timeout: 5m
  # Directories to skip
  skip-dirs:
    - dist
    - vendor

linters:
  enable:
    - govet            # vet diagnostics
    - staticcheck      # a go vet on steroids
    - errcheck         # check for unchecked errors
    - gosimple         # simplify code
    - unused           # unused code
    - deadcode         # find unused code
    - gocyclo          # cyclomatic complexity
    - gofmt            # gofmt simplicity
    - goimports        # missing or ungrouped imports
    - ineffassign      # detect ineffectual assignments
    - misspell         # find commonly misspelled words
    - structcheck      # find unused struct fields
    - varcheck         # find unused global variables/constants
  disable:
    - dupl             # false positives in small codebases
    - goconst          # not critical for this demo

linters-settings:
  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/ruslannv/google-search-agent

  gocyclo:
    min-complexity: 15

  misspell:
    locale: US

  errcheck:
    # ignore error checks in fmt.Printf family
    ignore-patterns:
      - '^fmt\.'

issues:
  # Stop on the first 0 issues per linter (0 = no limit)
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-use-default: false

  # Exclude generated files and test files from certain linters
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
